---
- name: Create IdM groups
  hosts: idm.lab.duncan-networks.com
  become: true
  gather_facts: false

  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all/vault.yml


  tasks:
    - name: Ensure IdM groups exist
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        state: present
      loop: "{{ idm_groups }}"